### ISSUE TITLE
atDude bugs found by Kim P

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/at_dude#26]
Feedback from Kim Perdikou testing the app:

- [x]  When you access if you are brand new to @sign - how do you find contacts to send them to?
They have to add the atsign of their contact, I can't find contacts for them but I can add an animation that highlights the add contact button with an instruction to add atsign.

- [x] For some reason - I can’t hear the Dude message when I tap the ball and so not sure what is getting sent
This was by design, You know which dude message based on the text that shows in the animation. eg "Hi dude" or "Awesome Dude". Sending a dude might get annoying if it plays the audio when you select the dude message type. Also, it will take away from the fun of discovering what the voice over is when someone sends you a dude message type you never heard before. We can discuss this on stand tomorrow.

- [x] It could not find @Kevin (ironic) so my screen below appeared  and say” atsign may no exist” instead of “not exist"
I'll make this update

- [ ] Due to no sound and my volume at high I sent two to @Barbara before I knew they had gone - It leaves you on the same screen and when I tried to get out I got the black screen of death - not sure exactly where I hit on the screen to try and get rid of sending to @barbara
I have to test to see if I reproduce the black screen to find the cause, the notification tells you when  sending the dude is successful but removing the contact when the dude is sent as we discussed should resolve this

- [x] Also it does not show me which @sign I am using on the front screen 
If it shows your atsign in the settings screen It might crowd up the UI to put your atsign on the main send dude screen. I'll raise this on stand tomorrow as well. It’s currently on the settings screen.

**Comment by CurtlyCritchlow** [comment]
I wasn't able to reproduce the black screen of death but the other bugs were fixed.
